### ISSUE TITLE
Adding additional data sets to VirtualBox installation?

### ISSUE THREAD

**Issue by oddrunpauline** [NatLibFi/Annif-tutorial#11]
Hi,
I have the VirtualBox version of the Annif tutorial, and have been through the mandatory exercises. I must say the tutorial is very useful and pedagogically presented!
Is there any way I can try Annif with any of my own vocabularies and data sets within that framework?
Oddrun

**Comment by juhoinkinen** [comment]
Hi,
Nice to hear you have found the tutorial useful :) 

There are a few options for getting vocabulary etc. files into the virtual machine:
- If the files are in a folder on your host computer, you can share the folder with the virtual machine. [This article](https://www.howtogeek.com/187703/how-to-access-folders-on-your-host-machine-from-an-ubuntu-virtual-machine-in-virtualbox/) shows how that can be done. (The username and password inside the virtual machine are both "annif", these are needed for the group assignment command `sudo adduser...`).
- If the files happen to be accessible from internet and not very large, it is probably most straightforward to simply download them from within the virtual machine.
- A work-around way is to copy the files from the host to an USB drive, and then mount the drive to  the virtual machine so the files can be accessed from there. (However when I tried this I could not mount an USB drive as it was not even visible to VirtualBox, but maybe that was just a problem with my computer.)

-Juho

**Comment by oddrunpauline** [comment]
Hi,
Thanks a lot! I opted for the second alternative (uploaded the relevant files to my Google disk, and downloaded with Firefox within the virtual machine), which worked fine. I'm very slowly wrapping my head around the fact that there are in fact  running 2 separate  machines on my computer :-) This also affects using the Web UI, by the fact that all text to be copied into the form must be got hold of from within the virtual machine ....
Oddrun

**Comment by osma** [comment]
VirtualBox does have clipboard integration, so it should be possible to copy and paste in between the host OS and the virtual machine. It works for me, when I'm using Ubuntu Linux (also) as the host OS. Maybe there is a problem with that if it doesn't work for you @oddrunpauline . The Annif-tutorial VM has the VirtualBox Guest Additions installed, but it's possible that there is e.g. a version mismatch, or you need to enable some setting in VirtualBox to make it work.

**Comment by osma** [comment]
To answer your original question: yes it should be possible to use your own vocabulary and data sets within the VM, as long as you can convert them into the right format (TSV or SKOS for the vocabulary, two possible formats for the documents). See here: https://github.com/NatLibFi/Annif/wiki/Corpus-formats
However, doing the conversion for your own data sets is going a bit outside the scope of the tutorial.

We have collected some corpora into the GitHub repository [Annif-corpora](https://github.com/NatLibFi/Annif-corpora) which also includes some of the conversion tools (usually Python scripts and Jupyter notebooks) we've written. These tools are always specific to the source data set because they come in various different formats, so you will most likely need to create your own conversion tools for your own data. It may also be possible to use Excel, LibreOffice Calc or OpenRefine to create the corpus TSV files.

The VM hard drive is limited to 20GB - it's possible to increase this but it takes a few steps. If you have downloaded the PDFs for either data set you can remove them to make more room for your own data.

**Comment by olufine** [comment]
Concerning Cut&Paste in VirtualBox: A bit more research indicates that the problem occurs when copying text at certain web-pages using a browser outside the VM with the aim to paste it into the Annif Web UI. Maybe it has something to do with restrictions on the source web-page? Examples:

1. The abstract https://www.tandfonline.com/doi/full/10.1080/15022250.2015.1015765 is **not** pastable to Annif Web UI
2. Text copied from https://www.nb.no/en/organisation-and-management-team/ **is** pastable into the Annif Web UI
2. Writing something into some desktop application outside VM is pastable to Annif Web UI
3. However, tried to copy the abstract in 1, then pasting it into some desktop application as text, then copying the resulting text. This was still not pastable to Annif Web UI. 
So, I ended up having to access the full text articles linked from my dataset from within the VM, which is a bit more cumbersome....

**Comment by osma** [comment]
Wow, that's a strange result @oddrunpauline! I can't think of any metadata (about restrictions etc) that would prevent this - it's more likely just some sort of technical incompatibility. Maybe some of the texts contain special characters that break the VirtualBox clipboard integration? Anyway, glad you found a solution that works for you, and that the copy/paste integration works at least some of the time :)

**Comment by olufine** [comment]
> To answer your original question: yes it should be possible to use your own vocabulary and data sets within the VM, as long as you can convert them into the right format (TSV or SKOS for the vocabulary, two possible formats for the documents). See here: https://github.com/NatLibFi/Annif/wiki/Corpus-formats
> However, doing the conversion for your own data sets is going a bit outside the scope of the tutorial.
> 
> We have collected some corpora into the GitHub repository [Annif-corpora](https://github.com/NatLibFi/Annif-corpora) which also includes some of the conversion tools (usually Python scripts and Jupyter notebooks) we've written. These tools are always specific to the source data set because they come in various different formats, so you will most likely need to create your own conversion tools for your own data. It may also be possible to use Excel, LibreOffice Calc, or OpenRefine to create the corpus TSV files.
> 
> The VM hard drive is limited to 20GB - it's possible to increase this but it takes a few steps. If you have downloaded the PDFs for either data set you can remove them to make more room for your own data.

Concerning using one's own data in Annif - I completely acknowledge that this lies outside the scope of the tutorial. Therefore, I have adapted my data to the Annif-required form, - writing a few chunks of code in Jupyter notebook did the trick :-) My question was only about getting the data into the VM. I also recognize that this setup is probably not ideal for extensive testing.  My problem is that I won't get admin rights to my machine, which runs Windows anyway. Hence, I saw using the VM as a convenient setup to experiment a bit on my own, before involving the (generally hard-to-get) IT people in our organization....

**Comment by osma** [comment]
That strategy makes perfect sense and I think you should be able to . There are some limitations of the VM compared to a native or Docker installation - for example, you may want to increase the memory and/or number of CPU cores available for the VM from the VirtualBox settings if you are working on large data sets, and inevitably virtualization will have some overhead - though Docker on Windows or Mac will also have this since it's also using a Linux VM layer internally.

If you need more disk space for the VM there are lots of tutorials for how to do it - search for "enlarge disk virtualbox" or similar. Basically you need to increase both the VDI virtual disk as well as the Linux partitions and file systems within it.

**Comment by olufine** [comment]
Thanks for the good advice! I'll take a look at the CPU and RAM situation. Also, I look forward to the help session on Wednesday.

**Comment by osma** [comment]
Closing this, please open a new issue if there are new problems.
